site_name: docsVTFK

theme:
  name: material
  language: nb
  logo: images/vtfk.png
  favicon: images/vtfk.png
  features:
    - navigation.tabs
    - search.suggest

plugins: 
  - search
  - blog:
      post_date_format: medium
      post_url_date_format: yyyy

repo_url: https://github.com/vtfk/docsVTFK
repo_name: vtfk/docsVTFK