site_name: docsVTFK

theme:
  name: material
  language: nb
  logo: images/vtfk.png
  favicon: images/vtfk.png

plugins: 
  - search
  - blog:
      post_date_format: medium
      post_url_date_format: yyyy
